let faqList = [
  ["Quero trabalhar com a ArqueoScallabis. Posso fazer uma candidatura espontânea?", "Sim. Para efetuar uma candidatura espontânea basta enviar o CV para geral@arqueoscallabis.pt. Todas as candidaturas serão alvo da nossa maior atenção."],
  ['Acabei agora a licenciatura em Arqueologia ou tenho pouca experiência na área. Posso enviar o meu CV?', 'Claro! Na ArqueoScallabis valorizamos toda a experiência dos candidatos, na área da Arqueologia e não só.'],
  ['Sou licenciado em Restauro ou Antropologia Biológica. Posso enviar o meu CV?', 'Claro! A ArqueoScallabis também desenvolve projeto na área do Restauro e áreas geográficas com grande probabilidade de aparecerem contextos onde a presença de um antropólogo é obrigatória.'],
  ['Tenho um projeto de construção para realizar. Preciso de serviços de Arqueologia?', 'Depende. Se o projeto estiver inserido numa zona de grau 1 do PDM, se se encontrar perto de uma Zona de Proteção Especial (ZEP) ou se afetar um imóvel classificado ou em vias de classificação, poderão ser necessários trabalhos arqueológicos prévios ou de acompanhamento dos trabalhos de obra. Se o projeto não se enquadra em nenhuma das anteriores situações, os serviços de Arqueologia só serão necessários se a autarquia local ou a Direção Geral do Património Cultural (DGPC) o determinarem. Em caso de dúvida pode sempre entrar em contato connosco através do email geral@arqueoscallabis.pt.'],
  ['O que faz um arqueólogo em obra?', 'O arqueólogo tem a função de identificar a presença de vestígios arqueológicos, registá-los e minimizar os impactos dos trabalhos de obra sobre os mesmos. Desta forma, tenta salvaguardar o possível interesse científico dos vestígios encontrados, ao mesmo tempo que assegura que os mesmos não interferem com o andamento dos trabalhos em execução.'],
  ['Quem tem a obrigação de pagar os serviços de Arqueologia, Restauro ou Antropologia, caso sejam necessários?', 'Qualquer serviço que venha a ser fornecido pela ArqueoScallabis será pago pela entidade contratante do mesmo, isto é, o Dono de Obra ou a Entidade Promotora da mesma. O pagamento de serviços prestado por uma empresa de Arqueologia não é diferente do pagamento de serviços de Ambiente, Higiene e Segurança (HSST), Topografia, ou outros necessários ao bom funcionamento da empreitada.']
] 

module.exports = faqList;